### ISSUE TITLE
Steam Input: Home button, gyro

### ISSUE THREAD

**Issue by purplebar0** [vanilla-wiiu/vanilla#104] opened 2024-11-15 23:28 UTC
As it stands, since Vanilla seems to use Steam Input if it has been started from Steam (more on that later...), there's the problem that Home button can't be bound to any button. This means that the suspend menu, and other functionality that requires the Home button can't be used.

I suppose a workaround of some sort will have to do, like assigning some keyboard key to Home if "Steam Deck Controller" (presumably Steam Input?) is being used, so that a chord, or back button for example can be bound to Home.

Furthermore, the gyro is inaccessible, and Steam Input only offers mapping it to thumbstick/mouse. On Cemu, it can be done using [SteamDeckGyroDSU](https://github.com/kmicki/SteamDeckGyroDSU), but as a more complicated alternative, Steam Input-native games seem to have direct gyro access.

And if you're curious how I even got it working on the Deck, I use a non-Steam shortcut in a desktop environment (not "Game Mode") like this:

`$term -e "/path/to/vanilla-gui"`

...where `$term` is the used terminal.

And finally, does "Steam Deck Controller" even correspond to Steam Input? If not, I shall rename the issue.

**Comment by itsmattkc** [comment] 2024-11-16 07:24
Duplicate of #79, discussion should probably continue there. I'm in the process of adding controller remapping functionality which should allow a home button to be set.

I'm not sure about Game Mode but I'm fairly sure I was able to get the gyro working out of the box in desktop mode.

**Closed by itsmattkc** 2024-11-16 07:24 UTC
