### ISSUE TITLE
No input and connect issues

### ISSUE THREAD

**Issue by flodor88000** [vanilla-wiiu/vanilla#113] opened 2024-12-05 11:39 UTC
I have a problem where if I connect to my wii u i see a black screen and sometimes i hear sound, but the screen appears once i trigger opening of the wii u menu (for example by resyncing, restarting the console or choosing "Wii U Menu" in virtual wii).
inputs don't work and when i press home button the gamepad is "disconected", also after i sync my laptop to the wiiu i get a notification saying "The console will now try to see if there is a gamepad" then after i press OK it says "unable to communicate with gamepad" but i can see and hear everything, besides inputs not working everything else seems to work fine.

But on my brothers laptop with identical wifi card, he used to have that problem for couple of days then it seemed to have resolved and he can use inputs and see the screen as soon as he click "connect".

specs: Lenovo legion y520 15ikbn, wifi card Intel Corporation Dual Band Wireless-AC 3165 Plus Bluetooth (rev 99)

logs:
[logs.txt](https://github.com/user-attachments/files/18022511/logs.txt)

**Comment by itsmattkc** [comment] 2024-12-06 04:45
Duplicate of #80

**Closed by itsmattkc** 2024-12-06 04:45 UTC
