### ISSUE TITLE
Poor contrast on Sync emojis

### ISSUE THREAD

**Issue by VoxelTek** [vanilla-wiiu/vanilla#35] opened 2024-06-20 04:40 UTC
When using a dark theme on Kubuntu 24.04, the Clubs and Spades emojis in the sync panel have poor contrast with the window and button, making them difficult to identify.
![image](https://github.com/vanilla-wiiu/vanilla/assets/53562267/d86e077b-644c-4493-9fc8-cc26876ee0d4)
One recommendation could be to change them to non-emoji Unicode characters, such as ♠♦♥♣ or ♤♢♡♧.

**Comment by itsmattkc** [comment] 2024-06-20 05:51
I'm not sure why it looks like that for you, this is what I see on my end and has always been what I intended it to look like:

![image](https://github.com/vanilla-wiiu/vanilla/assets/34096995/c15bb226-db69-4abf-bf46-78fbae76309f)

**Comment by itsmattkc** [comment] 2024-06-20 06:43
I actually quite specifically did _not_ use the emojis, if you copy the symbols in your post to into a UTF-8 hex converter like [this one](https://www.browserling.com/tools/utf8-to-hex), it produces the same bytes [that I use in the code](https://github.com/vanilla-wiiu/vanilla/blob/master/app/syncdialog.cpp#L9).

It seems something on your end is converting them _into_ emojis.

**Comment by VoxelTek** [comment] 2024-06-20 11:00
Hm, it seems that this does seem to be an issue on my end. Pasting the symbols into Kate (plain text editor) on my machine does show the first set of symbols as emojis, however it seems they aren't actually being converted to anything, just shown differently. I'll investigate this some more, see if maybe it's a font issue or something.

**Comment by VoxelTek** [comment] 2024-06-20 11:28
Strangely enough, this issue seems to only occur on Ubuntu. Not sure if it's just specifically Ubuntu 24.04, but trying the program on various machines, only the ones running Kubuntu 24.04 fail. Debian with Plasma and Debian with LXQt both run fine, and evidently your instance (which is presumably Arch with Plasma) runs fine. As such, I'm not entirely sure what's causing this issue, but I'll continue to investigate further.

**Comment by itsmattkc** [comment] 2024-06-20 17:43
Hmm I'm not sure either, but font issue seems likely. It's probably substituting emojis because it thinks the regular symbols are missing.

Do you see a difference with the prebuilt release vs compiling it yourself?

**Comment by VoxelTek** [comment] 2024-06-21 00:54
> Do you see a difference with the prebuilt release vs compiling it yourself?

Tried both, made sure I was on the latest version. Both are broken, but strangely the issue only seems to occur on 24.04. Kubuntu 22.04, Debian Bookworm, and Arch all seem to be fine, so I'm not sure if this is a Kubuntu 24.04-specific problem, or an issue with all Ubuntu 24.04-based distros.

**Comment by ToadKing** [comment] 2024-06-23 05:02
I think the issue is some fonts are using the emoji variant and some are not.

You should be able to force displaying of the text/monochrome variant though: https://www.codejam.info/2021/11/emoji-variation-selector.html

**Comment by itsmattkc** [comment] 2024-07-01 21:46
Fixed by #37

**Closed by itsmattkc** 2024-07-01 21:46 UTC
